from .diffwave import DiffWave
from .hifidiff import HifiDiff
from .hifidiffv2 import HifiDiffV2
from .hifidiffv3 import HifiDiffV3
from .hifidiffv4 import HifiDiffV4
from .hifidiffv5 import HifiDiffV5
from .hifidiffv7 import HifiDiffV7
from .hifidiffv7r1 import HifiDiffV7R1
from .hifidiffv8 import HifiDiffV8
from .hifidiffv9 import HifiDiffV9
from .hifidiffv9r1 import HifiDiffV9R1
from .hifidiffv9r2 import HifiDiffV9R2
from .hifidiffv9r3 import HifiDiffV9R3
from .hifidiffv9r4 import HifiDiffV9R4
from .hifidiffv9r5 import HifiDiffV9R5
from .hifidiffv9r6 import HifiDiffV9R6
from .hifidiffv9r7 import HifiDiffV9R7
from .hifidiffv9r8 import HifiDiffV9R8
from .hifidiffv9r9 import HifiDiffV9R9
from .hifidiffv9r10 import HifiDiffV9R10
from .hifidiffv9r11 import HifiDiffV9R11
from .hifidiffv9r12 import HifiDiffV9R12
from .hifidiffv9r13 import HifiDiffV9R13
from .wavegrad import WaveGrad